services:
  db:
    image: postgres:16-alpine
    container_name: ragnarok-docker
    environment:
      POSTGRES_DB: ragnarok
      POSTGRES_USER: igris
      POSTGRES_PASSWORD: igris
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro,z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  db_data: