services:
  db:
    image: postgres:16
    container_name: mud_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mud
      - POSTGRES_USER=mud_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - mud_pgdata:/var/lib/postgresql/data

volumes:
  mud_pgdata:
